# 2. Numpy

In [1]:
import numpy as np
import sys

s=range(1000)

print("Size of each element of list in bytes : ",sys.getsizeof(s))
print("Size of whole list in bytes : ",sys.getsizeof(s)*len(s))

d=np.arange(1000)

print("Size of each element of numpy array in bytes : ",d.itemsize)
print("Size of whole numpy array in bytes : ",d.size*d.itemsize)

Size of each element of list in bytes :  48
Size of whole list in bytes :  48000
Size of each element of numpy array in bytes :  4
Size of whole numpy array in bytes :  4000


In [8]:
import numpy as np
x=np.array([1,2,3,4,5])
print(x)
print(type(x))
print(x.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [14]:
print(x[2])

3


In [5]:
import numpy as np
arr=np.array(42)
print(arr)
print(type(arr))
print(arr.ndim)

42
<class 'numpy.ndarray'>
0


In [11]:
import numpy as np
y=np.array([[1,2,3,4,5]])
print(y)
print(type(y))
print(y.ndim)

[[1 2 3 4 5]]
<class 'numpy.ndarray'>
2


In [12]:
print(y[0,2])

3


In [15]:
import numpy as np
z=np.array([[[1,2,3,4,5]]])
print(z)
print(type(z))
print(z.ndim)

[[[1 2 3 4 5]]]
<class 'numpy.ndarray'>
3


In [16]:
print(z[0,0,2])

3


In [18]:
import numpy as np
z=np.array([[1,2,3,4],[5,6,7,8]])
print(z)
print(type(z))
print(z.ndim)
print()
print(z[1,2])

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2

7


In [40]:
import numpy as np
z1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(z1)
print(type(z1))
print(z1.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3


In [41]:
print(z1[1,1,1])

11


In [42]:
print(z1[1,1,2]+z1[0,1,1])

17


In [43]:
print(z1[0,1])

[4 5 6]


In [44]:
print(z1[0:2,0:2,0:2])

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


In [45]:
print(z1[0,1,3])

IndexError: index 3 is out of bounds for axis 2 with size 3

In [46]:
print(z1[1,-1])

[10 11 12]


In [47]:
import numpy as np
z=np.array([[1,2,3,4],[5,6,7,8]])
print(z)
print(type(z))
print(z.ndim)
print()
print(z[1,2])
print()
print(z[1,-1])
print()
print(z[-2,-2])
print()
print(z[1,0:3])
print()
print(z[1:,0:3])
print()
print(z[1:])
print()
print(z[1:,0:3:2])
print()
print(z[0:2,2])


[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2

7

8

3

[5 6 7]

[[5 6 7]]

[[5 6 7 8]]

[[5 7]]

[3 7]


**> Shape :**

In [48]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [49]:
import numpy as np
b=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b)
print(b.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [50]:
import numpy as np
c=np.array([1,2,3])
print(c)
print(c.shape)

[1 2 3]
(3,)


In [51]:
import numpy as np
x=np.array([1,2,3,4,5],ndmin=5)
print(x)
print(x.ndim)
print(x.shape)

[[[[[1 2 3 4 5]]]]]
5
(1, 1, 1, 1, 5)


**> Reshape :**

In [60]:
import numpy as np
y=np.array([1,2,3,4,5,6])
newarr=y.reshape(6,1)
print(newarr)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [61]:
newarr=y.reshape(1,6)
print(newarr)

[[1 2 3 4 5 6]]


In [62]:
newarr=y.reshape(2,3)
print(newarr)

[[1 2 3]
 [4 5 6]]


In [64]:
newarr=y.reshape(3,2).base
print(newarr)

[1 2 3 4 5 6]


In [65]:
import numpy as np
d=np.array([1,2,3,4,5,6])
newarr=d.reshape(2,-1)
print(newarr)

[[1 2 3]
 [4 5 6]]


In [66]:
newarr=d.reshape(-1,3)
print(newarr)

[[1 2 3]
 [4 5 6]]


In [67]:
import numpy as np
d=np.array([1,2,3,4,5,6])
for i in d:
    print(i)

1
2
3
4
5
6


In [68]:
import numpy as np
d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in d:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9


In [69]:
import numpy as np
d=np.array([[1,2,3],[4,5,6]])
for i in d:
    for j in i:
            print(j)

1
2
3
4
5
6


In [71]:
import numpy as np
d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(d):
    print(i)

1
2
3
4
5
6
7
8
9


In [72]:
import numpy as np
d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(d[:,:,::2]):
    print(i)

1
3
4
6
7
9


In [73]:
import numpy as np
d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(d[:,::2]):
    print(i)

1
2
3
7
8
9
