**> Concatenate() :**

In [1]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
arr=np.concatenate ((arr1,arr2,arr3))
print(arr)

[1 2 3 4 5 6 7 8 9]


In [3]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
arr=np.concatenate ((arr1,arr2))
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
arr=np.concatenate ((arr1,arr2),axis=0)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
arr=np.concatenate ((arr1,arr2),axis=1)
print(arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


**> split function :**

In [7]:
import numpy as np
arr1=np.array([1,2,3,4])
arr=np.array_split(arr1,4)
print(arr)

[array([1]), array([2]), array([3]), array([4])]


In [8]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr=np.array_split(arr1,2)
print(arr)

[array([1, 2, 3]), array([4, 5])]


In [9]:
import numpy as np
arr1=np.array([[1,2],[3,4],[5,6],[7,8]])
arr=np.array_split(arr1,4)
print(arr)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [10]:
import numpy as np
arr1=np.array([[1,2],[3,4],[5,6],[7,8]])
arr=np.array_split(arr1,3)
print(arr)

[array([[1, 2],
       [3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [11]:
import numpy as np
arr1=np.array([[1,2],[3,4],[5,6],[7,8]])
arr=np.array_split(arr1,4,axis=0)
print(arr)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [12]:
import numpy as np
arr1=np.array([[1,2],[3,4],[5,6],[7,8]])
arr=np.array_split(arr1,4,axis=1)
print(arr)

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int32), array([], shape=(4, 0), dtype=int32)]


In [14]:
import numpy as np
arr1=np.array([[1,2],[3,4],[5,6],[7,8]])
arr=np.array_split(arr1,3,axis=1)
print(arr)

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int32)]


**> Where() :**

In [16]:
import numpy as np
a=np.array([1,2,3,4,5,6,4,3])
x=np.where(a==4)
print(x)

(array([3, 6], dtype=int64),)


In [18]:
import numpy as np
a=np.array([[1,2],[3,4],[5,4],[6,4]])
x=np.where(a==4)
print(x)

(array([1, 2, 3], dtype=int64), array([1, 1, 1], dtype=int64))


In [21]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[4,8,9],[10,4,12]]])
x=np.where(a==4)
print(x)

(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64), array([0, 0, 1], dtype=int64))


In [22]:
import numpy as np
a=np.array([[1,2],[3,4],[5,4],[6,4]])
x=np.where(a%2==0)
print(x)

(array([0, 1, 2, 3, 3], dtype=int64), array([1, 1, 1, 0, 1], dtype=int64))


In [23]:
import numpy as np
a=np.array([1,2,4,3,6,5,2])
print(np.sort(a))
a2=np.array(['banana','apple','cherry','strawberry'])
print(np.sort(a2))

[1 2 2 3 4 5 6]
['apple' 'banana' 'cherry' 'strawberry']


In [24]:
a2=np.array([True,False,True])
print(np.sort(a2))

[False  True  True]


In [26]:
import numpy as np
a=np.array([1,2,4,3,6,5,2])
print(np.sort(a,axis=0))

[1 2 2 3 4 5 6]


In [27]:
import numpy as np
a=np.array([1,2,4,3,6,5,2])
print(np.sort(a,axis=-1))

[1 2 2 3 4 5 6]


In [29]:
import numpy as np
a=np.array([[3,4,3],[1,7,3],[4,2,5]])
x=np.sort(a)
print(x)

[[3 3 4]
 [1 3 7]
 [2 4 5]]


In [30]:
import numpy as np
a=np.array([[3,4,3],[1,7,3],[4,2,5]])
x=np.sort(a,axis=1)
print(x)

[[3 3 4]
 [1 3 7]
 [2 4 5]]


In [31]:
import numpy as np
a=np.array([[3,4,3],[1,7,3],[4,2,5]])
x=np.sort(a,axis=2)
print(x)

AxisError: axis 2 is out of bounds for array of dimension 2

In [32]:
import numpy as np
a=np.array([[3,4,3],[1,7,3],[4,2,5]])
x=np.sort(a,axis=0)
print(x)

[[1 2 3]
 [3 4 3]
 [4 7 5]]


In [34]:
import numpy as np
a=np.array([[3,4,3],[1,7,3],[4,2,5]])
x=np.sort(a,axis=None)
print(x)

[1 2 3 3 3 4 4 5 7]


In [35]:
import numpy as np
a=np.array([[[3,2,3],[7,9,3]],[[6,7,2],[9,6,4]]])
x=np.sort(a)
print(x)

[[[2 3 3]
  [3 7 9]]

 [[2 6 7]
  [4 6 9]]]


In [36]:
import numpy as np
a=np.array([[[3,2,3],[7,9,3]],[[6,7,2],[9,6,4]]])
x=np.sort(a,axis=2)
print(x)

[[[2 3 3]
  [3 7 9]]

 [[2 6 7]
  [4 6 9]]]


In [38]:
import numpy as np
a=np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,6,4]]])
x=np.sort(a,axis=0)
print(x)

[[[3 2 2]
  [7 6 3]]

 [[6 7 8]
  [9 9 4]]]


In [40]:
import numpy as np
a=np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,6,4]]])
x=np.sort(a,axis=1)
print(x)

[[[3 2 3]
  [7 9 8]]

 [[6 6 2]
  [9 7 4]]]


**> Random module:**

In [43]:
from numpy import random
x=random.randint(100)
print(x)

70


In [44]:
from numpy import random
x=random.randint(1,100)
print(x)

65


In [45]:
from numpy import random
x=random.randint(1,100,size=5)
print(x)

[49 38 68  7 46]


In [46]:
from numpy import random
x=random.randint(1,100,size=(3,5))
print(x)

[[23 46 25 59  6]
 [67 34 48 84 59]
 [65 64  9 88 71]]


In [47]:
from numpy import random
x=random.randint(1,100,size=(2,2,3))
print(x)

[[[74 51 86]
  [87 31 51]]

 [[96 33 23]
  [15 74  4]]]


In [48]:
from numpy import random
x=random.rand()
print(x)

0.4877794982501239


In [49]:
from numpy import random
x=random.rand(5)
print(x)

[0.97643791 0.22541829 0.752381   0.78788254 0.12746832]


In [50]:
from numpy import random
x=random.rand(3,5)
print(x)

[[0.67210374 0.66210507 0.83292106 0.5977775  0.2082722 ]
 [0.98491155 0.671743   0.19924172 0.62195097 0.82674828]
 [0.18001284 0.59915666 0.16339365 0.34922102 0.19855369]]


**> choice :**

In [51]:
from numpy import random
x=random.choice([1,3,5,7,9])
print(x)

3


In [54]:
from numpy import random
x=random.choice([1,3,5,7,9],size=5)
print(x)

[1 9 5 1 9]


- Task-1

In [3]:
from numpy import random
x=random.randint(1,100)
def guess():
    attempt=7
    for i in range(1,8):
        n=int(input("Enter the number between 1 to 100 : "))
        print("Attempt number = ",i)
        if n==x:
            print("Correct number")
            print("You won")
            break
        else:
            attempt=attempt-1
            print("Remain attempt= ",attempt)
            print()
            if attempt==0:
                print("You lose the game")
                print()
                print('Correct number is : ',x)
guess()

Enter the number between 1 to 100 : 56
Attempt number =  1
Remain attempt=  6

Enter the number between 1 to 100 : 58
Attempt number =  2
Remain attempt=  5

Enter the number between 1 to 100 : 15
Attempt number =  3
Remain attempt=  4

Enter the number between 1 to 100 : 36
Attempt number =  4
Remain attempt=  3

Enter the number between 1 to 100 : 86
Attempt number =  5
Remain attempt=  2

Enter the number between 1 to 100 : 25
Attempt number =  6
Remain attempt=  1

Enter the number between 1 to 100 : 4
Attempt number =  7
Remain attempt=  0

You lose the game

Correct number is :  5
